Repository CS2103-AY1819S1-F10-2/main, pull requests merged in 2018-10, with the labels that each got.

#125 Hide data(Censor sensitive information of customers)
  src/main/java/seedu/address/model/loan/Censor.java
  src/main/java/seedu/address/model/loan/Email.java
  src/main/java/seedu/address/model/loan/Nric.java
  src/main/java/seedu/address/model/loan/Phone.java
  src/main/java/seedu/address/ui/LoanCard.java
  src/main/resources/view/LoanListCard.fxml
  src/test/java/guitests/guihandles/LoanCardHandle.java
  src/test/java/seedu/address/model/loan/EmailTest.java
  src/test/java/seedu/address/model/loan/NricTest.java
  src/test/java/seedu/address/model/loan/PhoneTest.java
  src/test/java/seedu/address/ui/LoanCardTest.java
  src/test/java/seedu/address/ui/LoanListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: enhancement, priority.Medium, severity.Low

#105 Add LoanStatus enum
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/loan/Loan.java
  src/main/java/seedu/address/model/loan/LoanStatus.java
  src/main/java/seedu/address/model/loan/exceptions/SameLoanStatusException.java
  src/main/java/seedu/address/storage/XmlAdaptedLoan.java
  src/test/data/XmlSerializableLoanBookTest/duplicateLoanLoanBook.xml
  src/test/data/XmlSerializableLoanBookTest/invalidLoanLoanBook.xml
  src/test/data/XmlSerializableLoanBookTest/invalidLoanStatusLoanBook.xml
  src/test/data/XmlSerializableLoanBookTest/typicalLoanBook.xml
  src/test/data/XmlUtilTest/validLoan.xml
  src/test/data/XmlUtilTest/validLoanBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/model/loan/LoanStatusTest.java
  src/test/java/seedu/address/model/loan/LoanTest.java
  src/test/java/seedu/address/storage/XmlSerializableLoanBookTest.java
  src/test/java/seedu/address/testutil/LoanBuilder.java
  src/test/java/seedu/address/ui/LoanListPanelTest.java
Labels: enhancement, priority.High

#133 Fix Loan class data fields
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/loan/Loan.java
  src/main/java/seedu/address/model/loan/LoanTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedLoan.java
  src/main/java/seedu/address/ui/LoanCard.java
  src/main/resources/view/LoanListCard.fxml
  src/test/data/XmlSerializableLoanBookTest/duplicateLoanLoanBook.xml
  src/test/data/XmlSerializableLoanBookTest/typicalLoanBook.xml
  src/test/data/XmlUtilTest/invalidLoanField.xml
  src/test/data/XmlUtilTest/missingLoanField.xml
  src/test/data/XmlUtilTest/validLoan.xml
  src/test/data/XmlUtilTest/validLoanBook.xml
  src/test/java/guitests/guihandles/LoanCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/loan/LoanTest.java
  src/test/java/seedu/address/storage/XmlAdaptedLoanTest.java
  src/test/java/seedu/address/testutil/EditLoanDescriptorBuilder.java
  src/test/java/seedu/address/testutil/LoanBuilder.java
  src/test/java/seedu/address/testutil/LoanUtil.java
  src/test/java/seedu/address/testutil/TypicalLoans.java
  src/test/java/seedu/address/ui/LoanListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/LoanBookSystemTest.java
Labels: priority.High, severity.High

#144 Fix Nric parser
  src/main/java/loanbook/logic/parser/ParserUtil.java
Labels: type.Bug
