Repository CS2103-AY1819S1-F10-2/main, pull requests merged in 2018-11, with the labels that each got.

#157 Add colours to loan and bike lists
  src/main/java/loanbook/ui/LoanCard.java
  src/main/resources/view/BikeCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LoanCard.fxml
  src/test/java/guitests/guihandles/BikeListPanelHandle.java
  src/test/java/guitests/guihandles/ListPanelHandle.java
  src/test/java/guitests/guihandles/LoanListPanelHandle.java
Labels: UI

#156 Fix edit command not working with bikes
  src/main/java/loanbook/logic/commands/EditCommand.java
  src/main/java/loanbook/logic/parser/ParserUtil.java
  src/test/java/loanbook/logic/commands/AddCommandTest.java
  src/test/java/loanbook/logic/commands/CommandTestUtil.java
  src/test/java/loanbook/logic/commands/EditCommandTest.java
  src/test/java/loanbook/logic/commands/EditLoanDescriptorTest.java
Labels: priority.Medium, type.Bug

#245 Fix grammar and nits UG
  docs/UserGuide.adoc
Labels: Documentation, severity.Low

#246 Fix issues in UG examples
  docs/UserGuide.adoc
Labels: Documentation

#248 fix UG errors
  docs/UserGuide.adoc
Labels: Documentation

#251 Add summary functionality
  src/main/java/loanbook/logic/commands/Summary.java
  src/main/java/loanbook/logic/commands/SummaryCommand.java
  src/main/java/loanbook/logic/parser/LoanBookParser.java
  src/test/java/loanbook/logic/commands/SummaryCommandTest.java
Labels: priority.High

#252 Increase coverage across all files
  src/main/java/loanbook/logic/parser/ParserUtil.java
  src/main/java/loanbook/logic/parser/SetPasswordCommandParser.java
  src/main/java/loanbook/model/loan/exceptions/SameLoanStatusException.java
  src/main/java/loanbook/storage/XmlAdaptedLoan.java
  src/test/java/loanbook/logic/commands/ReturnCommandTest.java
  src/test/java/loanbook/logic/parser/LoanBookParserTest.java
  src/test/java/loanbook/logic/parser/SetPasswordCommandParserTest.java
  src/test/java/loanbook/model/loan/LoanIdTest.java
  src/test/java/loanbook/model/loan/LoanTest.java
  src/test/java/loanbook/model/loan/LoanTimeTest.java
  src/test/java/loanbook/storage/XmlAdaptedBikeTest.java
  src/test/java/loanbook/storage/XmlAdaptedLoanTest.java
  src/test/java/loanbook/testutil/TypicalLoanBook.java
Labels: priority.Low, severity.Low

#177 Move ResultDisplay to BrowserPanel
  src/main/resources/view/MainWindow.fxml
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: UI

#265 Update PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/deleteActivityDiagram.pptx
  docs/diagrams/setPassActivityDiagram.pptx
  docs/images/deleteActivityDiagram.png
  docs/images/setPassActivityDiagram.png
  docs/team/weineng.adoc
  docs/team/wn96.adoc
Labels: Documentation

#263 Update Documentations
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/LoanIndexWarning.png
  docs/images/ReturnFlow.png
  docs/images/ReturnSequence.png
  docs/images/ReturnSequenceLogic.png
Labels: Documentation

#280 Add Irham's PPP
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
  docs/team/xantho09.adoc
Labels: Documentation
